"""empty message

Revision ID: c3111871d685
Revises: None
Create Date: 2016-11-27 16:39:42.583911

"""

# revision identifiers, used by Alembic.
revision = 'c3111871d685'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserAccounts',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('UserName', sa.String(length=64), nullable=True),
    sa.Column('Password', sa.String(length=64), nullable=True),
    sa.Column('FBuserID', sa.String(length=32), nullable=True),
    sa.Column('FBAccessToken', sa.String(length=128), nullable=True),
    sa.Column('CreateDate', sa.DateTime(), nullable=True),
    sa.Column('ModifiedDate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('UserName')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserAccounts')
    ### end Alembic commands ###
